############################################################################
#
#   Copyright (c) 2026 Stalya. All rights reserved.
#
############################################################################

add_library(tpu_fwmgmt_proto INTERFACE)
target_include_directories(tpu_fwmgmt_proto INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
