#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (Optical Flow)
#
# @type Quadrotor Wide
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MPC_ACC_HOR 3.5
param set-default MPC_ACC_HOR_MAX 4.0
param set-default MPC_ACC_UP_MAX 3.5

param set-default MPC_JERK_AUTO 5.0
param set-default MPC_JERK_MAX 10.0
param set-default MPC_POS_MODE 3

param set-default MPC_YAWRAUTO_MAX 20
param set-default MPC_YAW_MODE 4

param set-default EKF2_IMU_POS_X 0.087
param set-default EKF2_IMU_POS_Y 0
param set-default EKF2_IMU_POS_Z -0.105

param set-default EKF2_GPS_POS_X -0.213
param set-default EKF2_GPS_POS_Y 0.107
param set-default EKF2_GPS_POS_Z -0.136

param set-default MC_PITCHRATE_MAX 150
param set-default MC_PITCHRATE_P 0.165
param set-default MC_PITCHRATE_I 0.225
param set-default MC_PITCHRATE_D 0.004
param set-default MC_PITCH_P 5.8

param set-default MC_ROLLRATE_MAX 150
param set-default MC_ROLLRATE_P 0.195
param set-default MC_ROLLRATE_I 0.275
param set-default MC_ROLLRATE_D 0.005
param set-default MC_ROLL_P 4.8

param set-default MC_YAWRATE_MAX 150
param set-default MC_YAWRATE_P 0.15
param set-default MC_YAWRATE_I 0.18
param set-default MC_YAWRATE_D 0.0
param set-default MC_YAW_P 6.5

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.41
param set-default CA_ROTOR0_PY 0.61
param set-default CA_ROTOR0_PZ 0
param set-default CA_ROTOR0_KM 0.05

param set-default CA_ROTOR1_PX -0.41
param set-default CA_ROTOR1_PY -0.62
param set-default CA_ROTOR1_PZ 0
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX 0.41
param set-default CA_ROTOR2_PY -0.61
param set-default CA_ROTOR2_PZ 0
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.41
param set-default CA_ROTOR3_PY 0.62
param set-default CA_ROTOR3_PZ 0
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
